### Create a new patient entity
POST localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe22",
  "email": "test22@example.com",
  "address": "123 main street22",
  "birthDate": "1990-01-01"
}

###